### ISSUE TITLE
Cuda error 77 when training Vgg16 on Kitti

### ISSUE THREAD

**Issue by zeroAska** [yuxng/SubCNN#11]
When I was running `./experiments/scripts/kitti_test_vgg16_rcnn_multiscale_6k8k.sh $GPU_ID` on a single Titan X GPU, I got such an error:

```
F0718 16:15:54.898038 16226 math_functions.cu:81] Check failed: error == cudaSuccess (77 vs.│
 0)  an illegal memory access was encountered
```

I don't quite understand why this happens. I tried on a few different computers with different GPUs, but the issue were still there. Any suggestions?

Thanks!

**Comment by zeroAska** [comment]
Solved by changing `SCALE` in the ` experiments/cfgs/...` from [3.0] to [1.0]

**Comment by yuxng** [comment]
Scale means the scaling factor of the image. With scale 3, the image is enlarged 3 times before feeding into the network. So it takes more memory.

**Comment by litingfeng** [comment]
@zeroAska , I changed SCALES_BASE TO `[1.0, 2.0]`, but I used rpn generated without changing anything which is default `[0.25, 0.5, 1.0, 2.0, 3.0]`. Then  when ran to     `test_net.py`  in `kitti_val_caffenet_rcnn_multiscale.txt` , error occurred 

`I0727 23:37:51.459563  3777 net.cpp:218] Memory required for data: 7306232
kitti_val
kitti_val roidb loaded from /home/Amber/SubCNN/fast-rcnn/data/cache/kitti_val_voxel_exemplars_RPN_region_proposal_roidb.pkl
F0727 23:37:52.692538  3777 blob.cpp:107] Check failed: data_ 
*** Check failure stack trace: ***
./experiments/scripts/kitti_val_caffenet_rcnn_multiscale.sh: line 22:  3777 Aborted                 (core dumped) ./tools/test_net.py --gpu $1 --def models/CaffeNet/kitti_val/test_rcnn_multiscale.prototxt --net output/kitti/kitti_train/caffenet_fast_rcnn_multiscale_kitti_iter_40000.caffemodel --imdb kitti_val --cfg experiments/cfgs/kitti_rcnn_multiscale1.yml
`

do you know why or how to fix it ? Is it possible that they have different scales like I said.
